AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Auth Service


Mappings:
  LogMap:
    PapertrailLog:
      stage: "logs7.papertrailapp.com:23213"
      prod: "should-be-prod-papertril-endpoint"

  UserTableCUMap:
    stage:
      wcumax: 1
      wcucrt: 1
      wcumin: 1
      rcumax: 1
      rcucrt: 1
      rcumin: 1
    prod:
      wcumax: should-be-prod-value
      wcucrt: should-be-prod-value
      wcumin: should-be-prod-value
      rcumax: should-be-prod-value
      rcucrt: should-be-prod-value
      rcumin: should-be-prod-value


Parameters:
  Env:
    Type: String
    Default: stage
    AllowedValues:
      - stage
      - prod
    Description: Env name

Globals:
    Function:
        Timeout: 300
        MemorySize: 512
        Runtime: go1.x

Resources:

  ScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - "application-autoscaling.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                  - "dynamodb:DescribeTable"
                  - "dynamodb:UpdateTable"
                  - "cloudwatch:PutMetricAlarm"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:GetMetricStatistics"
                  - "cloudwatch:SetAlarmState"
                  - "cloudwatch:DeleteAlarms"
                Resource: "*"

  StartAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ "-", [ !Ref Env, start-auth] ]
      Handler: start
      CodeUri: ./start-auth.zip
      Description: Start auth function
      Policies:
        - AmazonDynamoDBFullAccess
        - SecretsManagerReadWrite
        - AmazonKinesisFirehoseFullAccess
      Environment:
        Variables:
          ENV: !Ref Env
          PAPERTRAIL_LOG_ADDRESS: !FindInMap [LogMap, PapertrailLog, !Ref Env]
          USER_TABLE: !Ref UserTable
          DELIVERY_STREAM:
            Fn::ImportValue:
              !Join [ "-", [ !Ref Env, DeliveryStreamExportName] ]

      Events:
        HelloEvent:
          Type: Api
          Properties:
            Path: /start
            Method: post
      Tags:
        Company: Ringoid
        Service: auth
        Environment: !Ref Env

  CompleteAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ "-", [ !Ref Env, complete-auth] ]
      Handler: complete
      CodeUri: ./complete-auth.zip
      Description: Complete auth function
      Policies:
        - AmazonDynamoDBFullAccess
        - SecretsManagerReadWrite
      Environment:
        Variables:
          ENV: !Ref Env
          PAPERTRAIL_LOG_ADDRESS: !FindInMap [LogMap, PapertrailLog, !Ref Env]
      Events:
        HelloEvent:
          Type: Api
          Properties:
            Path: /complete
            Method: get
      Tags:
        Company: Ringoid
        Service: auth
        Environment: !Ref Env

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
          TableName: !Join [ "-", [ !Ref Env, Auth, UserTable] ]
          AttributeDefinitions:
            -
              AttributeName: phone
              AttributeType: S
            -
              AttributeName: user_id
              AttributeType: S
            -
              AttributeName: session_id
              AttributeType: S
          KeySchema:
            -
              AttributeName: phone
              KeyType: HASH

          ProvisionedThroughput:
            ReadCapacityUnits: !FindInMap [UserTableCUMap, !Ref Env, rcucrt]
            WriteCapacityUnits: !FindInMap [UserTableCUMap, !Ref Env, wcucrt]

          GlobalSecondaryIndexes:
            -
              IndexName: userIdGSI
              KeySchema:
                -
                  AttributeName: user_id
                  KeyType: HASH
              Projection:
                ProjectionType: ALL
              ProvisionedThroughput:
                ReadCapacityUnits: !FindInMap [UserTableCUMap, !Ref Env, rcucrt]
                WriteCapacityUnits: !FindInMap [UserTableCUMap, !Ref Env, wcucrt]
            -
              IndexName: sessionGSI
              KeySchema:
                -
                  AttributeName: session_id
                  KeyType: HASH
              Projection:
                ProjectionType: ALL
              ProvisionedThroughput:
                ReadCapacityUnits: !FindInMap [UserTableCUMap, !Ref Env, rcucrt]
                WriteCapacityUnits: !FindInMap [UserTableCUMap, !Ref Env, wcucrt]
          Tags:
            - Key: Company
              Value: Ringoid
            - Key: Service
              Value: auth
            - Key: Environment
              Value: !Ref Env

  UserTableWriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: UserTable
    Properties:
      MaxCapacity: !FindInMap [UserTableCUMap, !Ref Env, wcumax]
      MinCapacity: !FindInMap [UserTableCUMap, !Ref Env, wcumin]
      ResourceId: !Join
        - /
        - - table
          - !Join [ "-", [ !Ref Env, Auth, UserTable] ]
      RoleARN: !GetAtt
        - ScalingRole
        - Arn
      ScalableDimension: "dynamodb:table:WriteCapacityUnits"
      ServiceNamespace: dynamodb

  UserTableReadCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: UserTable
    Properties:
      MaxCapacity: !FindInMap [UserTableCUMap, !Ref Env, rcumax]
      MinCapacity: !FindInMap [UserTableCUMap, !Ref Env, rcumin]
      ResourceId: !Join
        - /
        - - table
          - !Join [ "-", [ !Ref Env, Auth, UserTable] ]
      RoleARN: !GetAtt
        - ScalingRole
        - Arn
      ScalableDimension: "dynamodb:table:ReadCapacityUnits"
      ServiceNamespace: dynamodb

  UserTableWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: UserTable
    Properties:
      PolicyName: WriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId:
        Ref: UserTableWriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization

  UserTableReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: UserTable
    Properties:
      PolicyName: ReadAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId:
        Ref: UserTableReadCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization

  UserTableUserIdGSIWriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: UserTable
    Properties:
      MaxCapacity: !FindInMap [UserTableCUMap, !Ref Env, wcumax]
      MinCapacity: !FindInMap [UserTableCUMap, !Ref Env, wcumin]
      ResourceId: !Join
        - /
        - - table
          - !Join [ "-", [ !Ref Env, Auth, UserTable] ]
          - index
          - userIdGSI
      RoleARN: !GetAtt
        - ScalingRole
        - Arn
      ScalableDimension: "dynamodb:index:WriteCapacityUnits"
      ServiceNamespace: dynamodb

  UserTableUserIdGSIReadCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: UserTable
    Properties:
      MaxCapacity: !FindInMap [UserTableCUMap, !Ref Env, rcumax]
      MinCapacity: !FindInMap [UserTableCUMap, !Ref Env, rcumin]
      ResourceId: !Join
        - /
        - - table
          - !Join [ "-", [ !Ref Env, Auth, UserTable] ]
          - index
          - userIdGSI
      RoleARN: !GetAtt
        - ScalingRole
        - Arn
      ScalableDimension: "dynamodb:index:ReadCapacityUnits"
      ServiceNamespace: dynamodb

  UserTableUserIdGSIWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: UserTable
    Properties:
      PolicyName: WriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId:
        Ref: UserTableUserIdGSIWriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization

  UserTableUserIdGSIReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: UserTable
    Properties:
      PolicyName: ReadAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId:
        Ref: UserTableUserIdGSIReadCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization

  UserTableSessionGSIWriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: UserTable
    Properties:
      MaxCapacity: !FindInMap [UserTableCUMap, !Ref Env, wcumax]
      MinCapacity: !FindInMap [UserTableCUMap, !Ref Env, wcumin]
      ResourceId: !Join
        - /
        - - table
          - !Join [ "-", [ !Ref Env, Auth, UserTable] ]
          - index
          - sessionGSI
      RoleARN: !GetAtt
        - ScalingRole
        - Arn
      ScalableDimension: "dynamodb:index:WriteCapacityUnits"
      ServiceNamespace: dynamodb

  UserTableSessionGSIReadCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: UserTable
    Properties:
      MaxCapacity: !FindInMap [UserTableCUMap, !Ref Env, rcumax]
      MinCapacity: !FindInMap [UserTableCUMap, !Ref Env, rcumin]
      ResourceId: !Join
        - /
        - - table
          - !Join [ "-", [ !Ref Env, Auth, UserTable] ]
          - index
          - sessionGSI
      RoleARN: !GetAtt
        - ScalingRole
        - Arn
      ScalableDimension: "dynamodb:index:ReadCapacityUnits"
      ServiceNamespace: dynamodb

  UserTableSessionGSIWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: UserTable
    Properties:
      PolicyName: WriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId:
        Ref: UserTableSessionGSIWriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization

  UserTableSessionGSIReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: UserTable
    Properties:
      PolicyName: ReadAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId:
        Ref: UserTableSessionGSIReadCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization

Outputs:

  StartAuthApi:
    Description: "API Gateway endpoint URL for Prod stage for start-auth function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/start"

  StartAuthFunction:
      Description: "start-auth lambda function ARN"
      Value: !GetAtt StartAuthFunction.Arn

  CompleteAuthApi:
    Description: "API Gateway endpoint URL for Prod stage for complete-auth function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/complete"

  CompleteAuthFunction:
      Description: "complete-auth lambda function ARN"
      Value: !GetAtt CompleteAuthFunction.Arn